version: '3'

services:
  web:
    build: 
      context: ./web/
    container_name: web
    ports:
      - 10001:4200
    volumes:
      # - project:/user/local/app
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro
    stdin_open: true
    tty: true
    networks:
      - dev-network

  stub:
    build:
      context: ./mocky/
    container_name: mocky
    volumes:
      - "./mocky/app:/node/app"
    ports:
      - "10010:4321"
    networks:
      - dev-network
    tty: true
    working_dir: /node
    entrypoint: node /node/app/mocky.js

  db:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "10002:27017"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  # project: {}
  mongodb-data: {}
